### ISSUE TITLE
    AccessDeniedException: The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access.

### ISSUE THREAD

**Issue by mrhouzlane** [aws/aws-encryption-sdk-javascript#1005]
I have created a CMK key that has authorizations and verified it's presence in the server.

I still have this error 

    ``` AccessDeniedException: The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access. ``` 

The region is us-west-2 and matches the key. 

The key encrypts and returns a value when doing : 
``` aws kms generate-data-key --key-id arn:aws:kms:us-west-****************/<keyId> --number-of-bytes 32 --profile default ```

**Comment by justplaz** [comment]
Hello @mrhouzlane! Thanks for reaching out. The error you have posted is an `AccessDeniedException` from AWS KMS. It appears that the IAM principal which the `default` profile refers has permission to call `generate-data-key` on the AWS KMS key you have provided, but the same credentials are not being used in the AWS Encryption SDK. It is also possible that the IAM principal has `generate-data-key` permission but is missing `encrypt`/`decrypt` permissions necessary for envelope encryption using the encrypted data key. 

You can read more about [setting credentials in the Javascript SDK here](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/getting-your-credentials.html) or read more about [troubleshooting AWS KMS access denied errors here](https://docs.aws.amazon.com/kms/latest/developerguide/policy-evaluation.html).
