### ISSUE TITLE
How do i authenticate with my credentials accessKey and cecretAccesskey?

### ISSUE THREAD

**Issue by bisfrim** [aws/aws-encryption-sdk-javascript#1093]
This is more of a question than an issue. How do i authenticate with my credentials **accesskey** and **secretaccesskey**

I tried doing this for my encrypt and decrypt function, but getting and an **AccessDeniedException** Not sure if i'm using the right functions from the sdk

import {
    KmsKeyringNode,
    buildClient,
    CommitmentPolicy,
    KMS,
  } from '@aws-crypto/client-node'

const client = new KMS({ region: 'us-east-1', accessKeyId: 'accesskey', secretAccessKey: 'secretaccesskey' })

const generatorKeyId = "arn key";

const keyring = new KmsKeyringNode({ client, generatorKeyId });

**Comment by ajewellamz** [comment]
Instead of

const client = new KMS({ region: 'us-east-1', accessKeyId: 'accesskey', secretAccessKey: 'secretaccesskey' })

you need to 

const client = new KMS({ region: 'us-east-1', credentials: {accessKeyId: 'accesskey', secretAccessKey: 'secretaccesskey' } })

**Comment by ajewellamz** [comment]
Did that work for you? Can we close this issue?

**Comment by bisfrim** [comment]
Sorry, it didn't work. I'm still getting the AccessDenied Exception

this is the example I'm trying to replicate.

```
import {
    KmsKeyringNode,
    buildClient,
    CommitmentPolicy,
    KMS
  } from '@aws-crypto/client-node'

  const { encrypt, decrypt } = buildClient(
    CommitmentPolicy.REQUIRE_ENCRYPT_REQUIRE_DECRYPT
  )
  const client = new KMS({ region: 'us-east-1', credentials: {accessKeyId: 'accessKeyId', secretAccessKey: 'secretAccessKey' } })

const generatorKeyId = "arn:aws:kms******************";


const keyring = new KmsKeyringNode({ generatorKeyId, client });

const encryptData = async (plainText, context) => {
    try {
      const { result } = await encrypt(keyring, plainText, { encryptionContext: context });
      return result;
    } catch (e) {
      console.log(e);
    }
  };

```


```
const decryptData = async (encryptedData, context) => {
    try {
      const { plaintext, messageHeader } = await decrypt(keyring, encryptedData);
      console.log("===== Message Header =======");
      console.log(JSON.stringify(messageHeader.encryptionContext));

  
      Object.entries(context).forEach(([key, value]) => {
        if (messageHeader.encryptionContext[key] === value) {
          console.log("it matched..");
        }
        if (messageHeader.encryptionContext[key] !== value)
          throw new Error("Encryption Context does not match expected values");
      });
  
      return plaintext.toString();
    } catch (e) {
      console.log(e);
    }
  };
```



But for some reason when I use the **aws-sdk** that seems to work fine. Not sure why **@aws-crypto/client-node** doesn't seem to work the same way. Is there anything I'm doing wrong?

```
import AWS from 'aws-sdk';
import crypto from 'crypto';

const kmsClient = new AWS.KMS({
   region: 'us-east-1',
   accessKeyId: 'accessKeyId',
   secretAccessKey: 'secretAccessKey'
 });
 const KeyId = 'arn:aws:kms***************'; // replace with your Customer Master Key ARN
 const KeySpec = 'AES_256';
 const data = 'this data will be encrypted';
```

**Comment by seebees** [comment]
If you can, in a browser, create a `const kmsClient = new AWS.KMS(...` and use it from you example to encrypt/and decrypt something, then I would suggest, using that exact AWS KMS SDK client in the keyring.

If that does not work, then I would look at the policy, there may be some encryption context condition.

**Comment by seebees** [comment]
Feel free to re-open if needed.
