### ISSUE TITLE
encrypt is not a function

### ISSUE THREAD

**Issue by mpalmaira** [aws/aws-encryption-sdk-javascript#1149]
```
const {
  KmsKeyringBrowser,
  encrypt,
  decrypt,
} = require("@aws-crypto/client-browser");

const generatorKeyId = "----KEY---";

const keyring = new KmsKeyringBrowser({
  generatorKeyId,
});

const context = {
  stage: "demo",
  purpose: "simple demonstration app",
  origin: "us-west-2",
};

const plaintext = new Uint8Array([1, 2, 3, 4, 5]);

const encryptData = async () => {
  const { result } = await encrypt(keyring, plaintext, {
    encryptionContext: context,
  });
};

encryptData();

```

I am getting an error that encrypt is not a function, when I am importing it at the top level.
the current version that I am using is     "@aws-crypto/client-browser": "^3.2.0",

thanks!

**Comment by justplaz** [comment]
Hi, thanks for reaching out.
It looks like you need to call buildClient() (see [this example](https://github.com/aws/aws-encryption-sdk-javascript/blob/master/modules/example-browser/src/kms_simple.ts#L25-L27)).
