### ISSUE TITLE
@aws-crypto/encrypt-node not available in the npm registry

### ISSUE THREAD

**Issue by amitkirdatt** [aws/aws-encryption-sdk-javascript#1187]
### Problem:

npm i @aws-crypto/encrypt-node results in a 404

<img width="630" alt="Screenshot 2023-07-14 at 2 52 44 PM" src="https://github.com/aws/aws-encryption-sdk-javascript/assets/6775052/7f7d66b1-c249-4298-be88-6de8d3525978">

**Comment by amitkirdatt** [comment]
Looks like the package is available now. That was weird!

**Comment by texastony** [comment]
Howdy @amitkirdatt ,
`npm` had a hick-up earlier today.
https://status.npmjs.org/incidents/jglnklhspsnm
As you have already noticed, `npm` has recovered.

Cheers,
AWS Crypto Tools
