### ISSUE TITLE
Uncaught Exception: "Cannot read properties of null (reading length)" when use encrypt function on lambda 20.x 

### ISSUE THREAD

**Issue by HeverFarber** [aws/aws-encryption-sdk-javascript#1374]
### Problem:
When we change AWS lambda to nodejs20.x runtime - we start to get `Uncaught Exception` when we use `encrypt` function - after a big effort I figured out it came from a package `stream-shift` which [uses a private field](https://github.com/nodejs/node/pull/50341#issuecomment-1890951456) of the buffer. An issue has occurred on node 20.11.0, which affects the functionality of the lambda.

You are exposed to these uses because you depend on https://www.npmjs.com/package/duplexify version 4.1.1

### Solution:
Update `duplexify` to version 4.1.3 which already fixes the version of `stream-shift`

[//]: #  (NOTE: If you believe this might be a security issue, please email aws-security@amazon.com instead of creating a GitHub issue. For more details, see the AWS Vulnerability Reporting Guide: https://aws.amazon.com/security/vulnerability-reporting/ )

**Comment by codyfrisch** [comment]
This issue just bit me as well.

**Comment by somersby10ml** [comment]
This issue just bit me as well.

**Comment by codyfrisch** [comment]
> This issue just bit me as well.

I added overrides to my package.json. Probably overkill how I did it but did not want to leave any path open. I've also alerted someone I know at AWS to the current state of this project which seems to be "unmaintained" at this point. Or at least "forgotten about" someplace.

    "overrides": {
        "@aws-crypto/encrypt-node@^4.0.0": {
            "duplexify": "^4.1.3"
        },
        "@aws-crypto/decrypt-node@^4.0.0": {
            "duplexify": "^4.1.3"
        },
        "@aws-crypto/client-node@^4.0.0": {
            "@aws-crypto/encrypt-node@^4.0.0": {
                "duplexify": "^4.1.3"
            },
            "@aws-crypto/decrypt-node@^4.0.0": {
                "duplexify": "^4.1.3"
            },
            "duplexify": "^4.1.3"
        },
        "duplexify": "^4.1.3"
    }

**Comment by rishav-karanjit** [comment]
This [PR](https://github.com/aws/aws-encryption-sdk-javascript/pull/1422/files#diff-09aa88ae3a0ddc37637feb58517df0b49db44821d7824e44e253710e37f357d2R23) updates the dependency. This update will be included in our next release. Thank you.

**Comment by rekotiira** [comment]
Also affecting us - is nobody maintaining this library anymore?

**Comment by codyfrisch** [comment]
> Also affecting us - is nobody maintaining this library anymore?

I do not believe this library should be considered active or usable in production going forward. Its clear it has been abandoned by AWS.

**Comment by codyfrisch** [comment]
@texastony you say this package is maintained. Why is fixing this issue not considered necessary to call the package maintained? This issue breaks the package for Node 20 - which is the current runtime for AWS Lambda. 

Sure we can work around this with overrides, but developers have an expectation to be able to update the package version and get things fixed...

**Comment by ajewellamz** [comment]
A new release went out yesterday.
This library now support Node 16, 18, 20 and 22
