### ISSUE TITLE
Compile errors of user of @aws-crypto/material-management with TypeScript 3.7.2

### ISSUE THREAD

**Issue by ankon** [aws/aws-encryption-sdk-javascript#232]
With @aws-crypto/client-node 1.0.1, TypeScript 3.7.2, on NodeJS 12.13.0 I'm getting this error when compiling our own sources:

~~~~
> tsc && tsc -p tsconfig.es6.json

node_modules/@aws-crypto/material-management-node/build/main/node_cryptographic_materials_manager.d.ts:3:21 - error TS2440: Import declaration conflicts with local declaration of 'NodeEncryptionMaterial'.

3 NodeAlgorithmSuite, NodeEncryptionMaterial, NodeDecryptionMaterial, KeyringNode, GetEncryptionMaterials, GetDecryptMaterials } from '@aws-crypto/material-management';
                      ~~~~~~~~~~~~~~~~~~~~~~

node_modules/@aws-crypto/material-management-node/build/main/node_cryptographic_materials_manager.d.ts:3:45 - error TS2440: Import declaration conflicts with local declaration of 'NodeDecryptionMaterial'.

3 NodeAlgorithmSuite, NodeEncryptionMaterial, NodeDecryptionMaterial, KeyringNode, GetEncryptionMaterials, GetDecryptMaterials } from '@aws-crypto/material-management';
                                              ~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors.
~~~~

`tsconfig.json`:
```json
{
	"extends": "./tsconfig.base.json",
	"compilerOptions": {
		"outDir": "dist"
	}
}
```

`tsconfig.es6.json`:
```json
{
	"extends": "./tsconfig.base.json",
	"compilerOptions": {
		"module": "es2015",
		"outDir": "dist.es6"
	}
}
```

`tsconfig.base.json`:
```json
{
	"extends": "tsconfig-collaborne",
	"compilerOptions": {
		"declaration": true
	},
	"include": [
		"src"
	]
}
```

(https://github.com/Collaborne/tsconfig-collaborne/blob/master/tsconfig.json has "tsconfig-collaborne")

**Comment by ankon** [comment]
Changing NodeJS to 10.16 doesn't change things.
Changing TypeScript to 3.6.4 "fixes" the compile error.

**Comment by seebees** [comment]
Thanks for the report!

**Comment by ankon** [comment]
If I may ask, what is the rough timeline for a release of the SDK with the fix for that problem?

**Comment by seebees** [comment]
@ankon Released to npm :)
