### ISSUE TITLE
Raw aes keyrings in a browse not processing  zero byte AES-GCM operations.

### ISSUE THREAD

**Issue by seebees** [aws/aws-encryption-sdk-javascript#237]
A few browsers, notably Safari (WebKit), do not properly handle zero byte AES-GCM operations.
In this case a fallback is required.
However for raw AES keyrings the master key is not properly handling this case.

Fix the import and use of the master key.
Add tests.

cc @khadir-syed moving the discussion to here to track the work.

**Comment by khadir-syed** [comment]
@seebees - Thank you for taking this up.

**Comment by khadir-syed** [comment]
Hi @seebees - Do we have any further update on this? I have seen some [pull](https://github.com/aws/aws-encryption-sdk-javascript/pull/239) request around this, but currently it is in blocked state. It will be helpful, if you can provide some update on this. Thank you for your support.

**Comment by seebees** [comment]
I'm trying to work out the best way to deliver an example.
When I test the code in the PR it works.
I can try and discuss merging the PR without an example,
but there are a few issues with the 1.4.1 version of MSR Crypto.
Delivering code without a clear way to use it feels like passing the buck. 
Crypto code is finicky, and I know whatever example I provide people will just copy without fully understanding the dependancy.
Sorry for the delay.
