### ISSUE TITLE
aws-crypto returns the base64 and not the real encrypted value

### ISSUE THREAD

**Issue by aldorea** [aws/aws-encryption-sdk-javascript#377]
I am encrypting sensitive data with the library @aws-crypto/client-node. I created an encryption service following the next example from aws docs with some modifications since I need to store encrypted data in MongoDB. This is the encryption service.
```
async encrypt(data: string): Promise<string> {`
    const { result } = await encrypt(this.keyring, data, {
      encryptionContext: context,
    });

    return result.toString('base64');
  }

  async decrypt(data: string): Promise<string> {
      const { plaintext, messageHeader } = await decrypt(this.keyring, data, {
        encoding: 'base64'
      });
      const { encryptionContext } = messageHeader;
      Object.entries(context).forEach(([key, value]) => {
        // if (encryptionContext[key] === value) console.log('Matched')
        if (encryptionContext[key] !== value)
          throw new Error('Encryption Context does not match expected values');
      });

   return plaintext.toString('utf8');
}
```

I am encrypting and decrypting data in the mongoose hooks without problems as you can see in the example.
```
schema.pre<Sample>('save', async function() {
    this.heartRate = await encryptionService.encrypt(this.heartRate);
 });

 schema.post<Sample>('save', async function(doc) {
    doc.heartRate = await encryptionService.decrypt(doc.heartRate);
 });
```

The problem comes when I have to decrypt the data that I get from an aggregate query. The decrypt method of the encryptionService returns the base64 string which is stored in db.

Has anyone had this problem? Thanks in advance.

**Comment by aldorea** [comment]
> I am encrypting sensitive data with the library @aws-crypto/client-node. I created an encryption service following the next example from aws docs with some modifications since I need to store encrypted data in MongoDB. This is the encryption service.
> 
> ```
> async encrypt(data: string): Promise<string> {`
>     const { result } = await encrypt(this.keyring, data, {
>       encryptionContext: context,
>     });
> 
>     return result.toString('base64');
>   }
> 
>   async decrypt(data: string): Promise<string> {
>       const { plaintext, messageHeader } = await decrypt(this.keyring, data, {
>         encoding: 'base64'
>       });
>       const { encryptionContext } = messageHeader;
>       Object.entries(context).forEach(([key, value]) => {
>         // if (encryptionContext[key] === value) console.log('Matched')
>         if (encryptionContext[key] !== value)
>           throw new Error('Encryption Context does not match expected values');
>       });
> 
>    return plaintext.toString('utf8');
> }
> ```
> 
> I am encrypting and decrypting data in the mongoose hooks without problems as you can see in the example.
> 
> ```
> schema.pre<Sample>('save', async function() {
>     this.heartRate = await encryptionService.encrypt(this.heartRate);
>  });
> 
>  schema.post<Sample>('save', async function(doc) {
>     doc.heartRate = await encryptionService.decrypt(doc.heartRate);
>  });
> ```
> 
> The problem comes when I have to decrypt the data that I get from an aggregate query. The decrypt method of the encryptionService returns the base64 string which is stored in db.
> 
> Has anyone had this problem? Thanks in advance.

**Comment by aldorea** [comment]
Error updating issue

**Comment by seebees** [comment]
Just putting encrypted data into a database is often not enough to provide the security properties you expect. 
You will need to do extra work to ensure the encrypted data you have is the right data, before you take any action involving the decrypted data itself. One way to do so is to put the keys associated with each access pattern into the encryption context when you encrypt the data, and verify that the key’s value in the encryption context matches what you used to access the encrypted data when you decrypt it (see the Dynamo DB Encryption Client for an example).

I don't have any specific experience with your problem. In your code, it is not clear where `context` is defined. Also, the base64 value that is returned, is that decrypt-able? Have you tried decryption that? Are you sure that your `decrypt` method is getting called? And that there are no errors?

**Comment by aldorea** [comment]
@seebees  the problem is not with sdk. I realized that mongoose hooks are executing twice so I need to decrypt twice to get the original data.

**Comment by seebees** [comment]
That sounds sub-optimal :(
If you get a solution I'd love to get it captured here for others :)
But it sounds like I can close this.
Feel free to re-open if you need to.
