### ISSUE TITLE
implementation: re-designing the AWS KMS keyring

### ISSUE THREAD

**Issue by acioc** [aws/aws-encryption-sdk-javascript#380]
Per awslabs/aws-encryption-sdk-specification#165 , we are re-implementing the AWS KMS keyring.

This should be placed in a new AWS KMS namespace

**Comment by seebees** [comment]
#298 and #367 will be subsumed into this work.

**Comment by seebees** [comment]
Our plan is to track compliance to the specification with a new mechanism
