### ISSUE TITLE
Fix maxBodySize Decrypt input to be inclusive

### ISSUE THREAD

**Issue by lavaleri** [aws/aws-encryption-sdk-javascript#389]
See https://github.com/awslabs/aws-encryption-sdk-specification/issues/183

**Comment by seebees** [comment]
The logic is already inclusive.
https://github.com/aws/aws-encryption-sdk-javascript/blob/f0b58dc143144432cd416d6833ca7b7435e3923d/modules/decrypt-node/src/verify_stream.ts#L132
