### ISSUE TITLE
Accept local CMC capacity value of 0

### ISSUE THREAD

**Issue by alex-chew** [aws/aws-encryption-sdk-javascript#397]
Follow-up to awslabs/aws-encryption-sdk-specification/pull/166.

Current implementation: https://github.com/aws/aws-encryption-sdk-javascript/blob/20045ca0cae056184ea9cdfdafb83dbc811c22b3/modules/cache-material/src/get_local_cryptographic_materials_cache.ts#L21-L33

The LRU constructor interprets `max: 0` as `max: Inifinity`.

**Comment by seebees** [comment]
Our plan is to track compliance to the specification with a new mechanism
