### ISSUE TITLE
Support alternative implementations of CryptographicMaterialsCache

### ISSUE THREAD

**Issue by ntharakan** [aws/aws-encryption-sdk-javascript#468]
The interface for the `CryptographicMaterialsCache` is currently implemented as an in memory cache. This doesn't work very well when used with AWS Lambda, given the short lifespan of Lambdas. Is it possible to make this `CryptographicMaterialsCache` interface asynchronous? Thereby allowing users to write their own cache implementations (backed by alternative stores like Redis) and pass that into the `NodeCachingMaterialsManager`?

**Comment by seebees** [comment]
Cryptographically speaking a distributed cache is significantly more complicated.
This is best handled at the CMM level, and not in a simple pluggable cache.

A design discussion for this would happen here: https://github.com/awslabs/aws-encryption-sdk-specification
Because whatever we create should be interoperable with other implementations of the AWS Encryption SDK.

That said, when you say "short lifespan of Lambdas" what do you mean?

It is easy to store a cache in the Lambda across events.
In JS this is just a closure outside of the handler.
A little like this:

```javascript
const client = require('@aws-crypto/client-node')
const keyring = new client.KmsKeyringNode({ generatorKeyId, keyIds })
const cache = client.getLocalCryptographicMaterialsCache(100)
const cachingCMM = new NodeCachingMaterialsManager({
  backingMaterials: keyring,
  cache
})

module.exports.handler = (event) => {
  // Your logic here
}
```

**Comment by ntharakan** [comment]
The implementation we tried is similar to your suggestion. The main difference for us is that the keyring is determined by the data in `event`. It can change between invocations. So while we can create the materials cache as above we create the cmm in the handler... 

Regarding the short lifespan comment. I was referring to this:
<img width="800" alt="Overview-Successful-Invokes" src="https://user-images.githubusercontent.com/11451405/101229432-13f6e600-3655-11eb-883b-e2763b7315e4.png">
Each materials cache is tied to this lifecycle which is why I was looking for something that used an external store.

**Comment by seebees** [comment]
Sharing a cache across different keyrings is drifting into dangerous territory :)
Obviously using material cached from keyring A for a message with keyring B is bad.
However, if you have a tractable number of keyrings, you could use the `partition` option.

```typescript
declare const keyringA: Keyring
const keyringApartition = uuid()

module.exports.handler = (event) => {
  const [backingMaterials, partition] = getKeyring(event)

  const cachingCMM = new NodeCachingMaterialsManager({
    backingMaterials,
    cache,
    partition
  })
  // Your logic here
}

function getKeyring(event) {
  //Your logic to pick the right keyring here
  return [keyringA, keyringApartition]
}
```

I'm not sure what you mean with that diagram.
Unless you are saying that Lambda just re-cycles containers faster than is useful for you?
Could you make a Lambda for each keyring,
and then route the requests to the appropriate Lambda?
That is more functions, but it has a simpler security profile.

**Comment by ntharakan** [comment]
Thanks for the sample, yeah we used the partition option. Yes, the lambda re-cycles too quickly. I don't think it's viable for us to do a Lambda for each keyring.
