### ISSUE TITLE
[Question] default encryption algorithm used in encrypt?

### ISSUE THREAD

**Issue by viyatgandhi** [aws/aws-encryption-sdk-javascript#477]
I am trying to implement encryption sdk for my application using simple KMS method.

https://github.com/aws/aws-encryption-sdk-javascript/blob/master/modules/example-node/src/kms_simple.ts

But I don't see any documentation around default encryption algorithm used in `encrypt` method?

Didn't find any clue from here: https://github.com/aws/aws-encryption-sdk-javascript/blob/master/modules/encrypt-node/src/encrypt_stream.ts

**Comment by acioc** [comment]
Our supported algorithms are listed on https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/supported-algorithms.html By default, the AWS Encryption SDK uses an algorithm suite with AES-GCM with an HMAC-based extract-and-expand key derivation function ([HKDF](https://en.wikipedia.org/wiki/HKDF)), signing, and a 256-bit encryption key. Using `REQUIRE_ENCRYPT_REQUIRE_DECRYPT` as noted in the example enforces a [commitment policy](https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/concepts.html#commitment-policy) with [key commitment](https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/concepts.html#key-commitment).

Please re-open this issue (or cut us a new one) if you have any other questions.
