### ISSUE TITLE
@aws-crypto/kms-keyring-browser installs the entire AWS-SDK increasing the size of the final bundle

### ISSUE THREAD

**Issue by Djvash01** [aws/aws-encryption-sdk-javascript#535]
The @aws-crypto/client-browser package is used for an angular web application.

![image](https://user-images.githubusercontent.com/17219181/107569586-7a006c00-6bb6-11eb-8153-ccd1b70df423.png)

The module @aws-crypto/kms-keyring-browser installs all aws-sdk, greatly increasing the size of the final app package.

[package.json](https://github.com/aws/aws-encryption-sdk-javascript/blob/master/modules/kms-keyring-browser/package.json)

`"dependencies": {`
`    "@aws-crypto/kms-keyring": "file:../kms-keyring",`
`    "@aws-crypto/material-management-browser": "file:../material-management-browser",`
`    "@aws-crypto/web-crypto-backend": "file:../web-crypto-backend",`
`    "aws-sdk": "^2.650.0",`
`    "tslib": "^1.11.1"`
`  }`

![image](https://user-images.githubusercontent.com/17219181/107569080-e2028280-6bb5-11eb-86ee-b64ca4cddcbb.png)

Why not just use the KMS client for the client-browser?

[Modular packages in AWS SDK for JavaScript](https://aws.amazon.com/es/blogs/developer/modular-packages-in-aws-sdk-for-javascript/)

[AWS SDK for JavaScript v3](https://github.com/aws/aws-sdk-js-v3)

[@aws-sdk/client-kms](https://github.com/aws/aws-sdk-js-v3/tree/master/clients/client-kms)

**Comment by seebees** [comment]
If you do not need to use the AWS KMS Keyrings you do not need to include them.

If you are using the ESDK in the browser, for example,
and you _only_ need to encrypt with the Raw RSA Keyring
then you could only require
`@aws-crypto/encrypt`
`@aws-crypto/raw-rsa-keyring-browser`
