### ISSUE TITLE
Custom Endpoints

### ISSUE THREAD

**Issue by kmai** [aws/aws-encryption-sdk-javascript#549]
Hey there, 

I've been trying to find documentation regarding the usage of custom endpoints (VPC Endpoints, Localstack, etc) for this SDK without luck.

Is this supported? Do you have an example code snippet for this?

**Comment by alex-chew** [comment]
Hi @kmai, just to clarify - are you asking about using KMS keyrings with custom KMS endpoints?

**Comment by kmai** [comment]
Indeed. But it could be any configuration for the client, not only the endpoint.

**Comment by seebees** [comment]
The AWS KMS keyrings take a `ClientProvider` interface that returns SDK clients.
This interface can be use to create an SDK client with any configuration you need.

See: https://github.com/aws/aws-encryption-sdk-javascript/blob/master/modules/kms-keyring/src/kms_keyring.ts#L48

Here is the def for `ClientProvider` is https://github.com/aws/aws-encryption-sdk-javascript/blob/master/modules/kms-keyring/src/kms_client_supplier.ts#L22-L25
