### ISSUE TITLE
Incomplete Header

### ISSUE THREAD

**Issue by tzlillmnd** [aws/aws-encryption-sdk-javascript#551]
Hi guys,
I am using this package for a month and I suddenly started experiencing `parse_header_stream.ts#_flush` error: `Incomplete Header` during decryption. I can see that it happens sometimes and sometimes not.  

I don't use s3, just the key arn `const { plaintext, messageHeader } = await decrypt(keyring, ...))`

What can be the cause of it?

**Comment by alex-chew** [comment]
This error typically occurs when you try to decrypt an incomplete message.

Can you clarify what you mean by "it happens sometimes and sometimes not"? Are you seeing the error on some message but not others? Or are you decrypting a single message that sometimes fails and sometimes succeeds?

**Comment by tzlillmnd** [comment]
Exactly - _decrypting a single message that sometimes fails and sometimes succeeds_

**Comment by seebees** [comment]
It sounds like the failures are timeouts.
Either to AWS KMS or to the underlying stream of bytes.
