### ISSUE TITLE
Encrypted Data Decryption Latency 

### ISSUE THREAD

**Issue by LCA-95** [aws/aws-encryption-sdk-javascript#554]
Hi Guys, 

Currently i am using AWS Encryption SDK to store encrypted value in Dynamodb. 
At the same time, will have a lambda service that get and return the raw decrypted data from dynamodb and show in UI.
However, AWS Encryption SDK took more than 10 seconds to decrypt around 50~100 records as the decryption process is decrypting the data 1 by 1.

As per the decryption time latency incurred which causes bad user experience and waiting, is there any method to decrypt an array of encrypted value with single call at the same time? Or what is the suggested method to reduce the decryption latency as the number of records will be increase from time to time?

Thanks in advanced!

**Comment by seebees** [comment]
The `decrypt` function is just a `Promise` so `Promise.all[decrypt(...), decrypt(...),...]` will process the `decrypt` in parallel.

However, note that the optimal parallelization is unlikely to be every element in your array.
Especially depending on the size of your Lambda.

Libraries like `Bluebird` have (http://bluebirdjs.com/docs/api/promise.map.html) have a `concurrency` that should help.
