### ISSUE TITLE
AWS encryption /Decryption issue

### ISSUE THREAD

**Issue by Iqbal-125** [aws/aws-encryption-sdk-javascript#576]
Using Secure IVR documentation provided by AWS encrypted the account number in contact flow

https://aws.amazon.com/blogs/contact-center/creating-a-secure-ivr-solution-with-amazon-connect/
 Using open sal created public key , certificate and private key

Note : private key begin as ----BEGIN ENCRYPTED PRIVATE KEY----

 ,but when we try to decrypt using node js the decryption is not happening as expected.

My private key is starting with ----BEGIN ENCRYPTED PRIVATE KEY ------- using private key I'm trying to decrypt the value,am getting asn1 encoding is too long error.

**Comment by texastony** [comment]
Howdy @Iqbal-125,

If you are still having an issue, please re-open and comment with more details.

Much Obliged,
AWS Crypto Tools
