### ISSUE TITLE
SDK throws errors with minimal example

### ISSUE THREAD

**Issue by xird** [aws/aws-encryption-sdk-javascript#594]
I tried to take the encryption SDK into use in a TypeScript/Express application I'm developing, but after uploading the Docker container to AWS ECS, the whole container crashed with a not-very-helpful error message:

```
2021-04-29 11:43:02 npm ERR! A complete log of this run can be found in:
2021-04-29 11:43:02 npm ERR! /root/.npm/_logs/2021-04-29T08_43_02_807Z-debug.log
2021-04-29 11:43:02 npm ERR! my-application@1.0.0 start: `node dist/src/server.js`
2021-04-29 11:43:02 npm ERR! Exit status 1
2021-04-29 11:43:02 npm ERR!
2021-04-29 11:43:02 npm ERR! Failed at the my-application@1.0.0 start script.
2021-04-29 11:43:02 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-04-29 11:43:02 npm ERR! code ELIFECYCLE
2021-04-29 11:43:02 npm ERR! errno 1
2021-04-29 11:43:02 /usr/src/app/node_modules/@aws-crypto/material-management/build/main/needs.js:18
2021-04-29 11:43:02 throw new Err(errorMessage);
```

On my local machine the app runs fine.

I then added some logging to the needs.js file mentioned in the error message, and noticed that the SDK is throwing a _lot_ of errors, which are then apparently silently swallowed.

This behaviour can be reproduced with the attached test application. The cp-command just replaces the library file with one that has extra logging.

- Unzip the package
- Replace the key ARN in test.ts with the ARN of a symmetric KMS CMK that you have access to
- npm ci
- cp needs.js node_modules/@aws-crypto/material-management/build/main/
- npx ts-node test.ts

```
condition: true
errorMessage: Curve not supported at this time
condition: true
errorMessage: Curve not supported at this time
condition: REQUIRE_ENCRYPT_REQUIRE_DECRYPT
errorMessage: Invalid commitment policy.
condition: REQUIRE_ENCRYPT_REQUIRE_DECRYPT
errorMessage: Invalid commitment policy.
condition: true
errorMessage: new KmsKeyring is not allowed
condition: true
errorMessage: Noop keyring is not allowed: Set a keyId or discovery
condition: true
errorMessage: A keyring can be either a Discovery or have keyIds configured.
condition: true
errorMessage: Account and partition decrypt filtering are only supported when discovery === true
condition: true
errorMessage: A discovery filter must be able to match something.
condition: true
errorMessage: KMS key arn must be a string.
[snipped 172 more lines of errors]
Base64-encoded:
```

What's going on here?

[test.zip](https://github.com/aws/aws-encryption-sdk-javascript/files/6397594/test.zip)

**Comment by xird** [comment]
So the ECS crashing was caused by something else, but the above is still a bit weird in my book.

**Comment by texastony** [comment]
Howdy @xird ,

We apologize for the slow response.
`needs` throws an Error when the condition is FALSE, not True. 
Read it as "the ESDK needs the condition or Error with message".

Much Obliged,
AWS Crypto Tools
