### ISSUE TITLE
Facing TypeError: `getEncryptionMaterials` is not a function

### ISSUE THREAD

**Issue by GRBurst** [aws/aws-encryption-sdk-javascript#638]
Hey 👋 

I try to run an example with minimal configuration:
```javascript
  const keyring = new KmsKeyringNode({ generatorKeyId, keyIds })
  const cache = getLocalCryptographicMaterialsCache(100)

  const cachingCMM = new NodeCachingMaterialsManager({
    backingMaterials: keyring,
    cache,
    60*1000
  })

  const cleartext = 'asdf'

  const { result } = await encrypt(cachingCMM, cleartext, {
  encryptionContext: {},
})
  ```

However, I am facing the following error:
```
    "errorType": "TypeError",
    "errorMessage": "r.getEncryptionMaterials is not a function"
 ```
 
I do not touch anything else. The used package versions is `"@aws-crypto/client-node": "^2.3.0"`.

Any suggestions what might cause it?

**Comment by texastony** [comment]
GRBurst

Thanks for reaching out. I am unable to reproduce this issue with just the information you have given me.

Could you describe your build environment/system?

Are you compiling TypeScript to JS? If so, could you show me your tsconfig? 

I set up a bare minimum code base to run the example ([which is the `caching_cmm` example](https://github.com/aws/aws-encryption-sdk-javascript/blob/master/modules/example-node/src/caching_cmm.ts)).

I had to provide the field names to every parameter passed to `NodeCachingMaterialsManager`.

i.e.:
```
    const cachingCMM = new NodeCachingMaterialsManager({
                                                           backingMaterials: keyring,
                                                           cache: cache,
                                                           maxAge: 60*1000
    })
```

Of the 5 parameters to `NodeCachingMaterialsManager`, 3 are `number` types. 

While only one is required (`maxAge`), I still had to annotate it.

I tried with both TypeScript and plain JS (as a module, so I could import/export). In both occasions, the `maxAge` field name was necessary to run the test.

My work is attached as a zip. There are two commits in the zip's repo, one with TS, and the other with JS module.

Try giving the field names to the `NodeCachingMaterialsManager`. If that does not help, re-open this issue, and let us know more about your build environment (TypeScript/JS/Module).
[esdk-js-638.zip](https://github.com/aws/aws-encryption-sdk-javascript/files/6794318/esdk-js-638.zip)
