### ISSUE TITLE
Compile errors @aws-crypto/material-management with @types/node >= 16.0.2

### ISSUE THREAD

**Issue by cernytomas** [aws/aws-encryption-sdk-javascript#722]
### Problem:

Cannot build Typescript project using @aws-crypto/material-management and @types/node >= 16.0.2

```
node_modules/@aws-crypto/material-management-node/build/main/src/material_helpers.d.ts:3:10 - error TS2724: '"crypto"' has no exported member named 'Signer'. Did you mean 'Sign'?

3 import { Signer, Verify, createCipheriv, createDecipheriv } from 'crypto';
           ~~~~~~

  node_modules/@types/node/crypto.d.ts:1265:11
    1265     class Sign extends stream.Writable {
                   ~~~~
    'Sign' is declared here.
```

### Solution:

This issue is due to wrong type definition of crypto `Sign` class (previously `Signer`) fixed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54394 
released with @types/node@16.0.2

Update @types/node to version 16.0.2 or higher
Rename `Signer` to `Sign`

This solution will be breaking change for developers using @types/node < 16.0.2

**Comment by tomasstrejcek** [comment]
This can probably be closed then? :)

**Comment by texastony** [comment]
Howdy @sandfox , @tomasstrejcek , @cernytomas 

The latest release of the [ESDK-JavaScript](https://github.com/aws/aws-encryption-sdk-javascript/releases/tag/v3.1.0) supports Node 16. 
If there are still problems with using our library with `@types/node >= 16`, please re-open or create a new issue.

Much Obliged,
AWS Crypto Tools
