### ISSUE TITLE
@aws-crypto/client-browser compilation error

### ISSUE THREAD

**Issue by leopinzon** [aws/aws-encryption-sdk-javascript#835]
I'm working on a ReactJS project and I developed a strings encryption/decryption helper which makes use of the AWS KMS crypto library.

I haven't been able to compile the project for errors on the AWS library itself. I have the following error when using the @aws-crypto/client-browser module:
```
./node_modules/@aws-crypto/kms-keyring/build/module/src/kms_mrk_keyring.js 11:9
Module parse failed: Unexpected token (11:9)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   //# interface.md#interface)
|   extends BaseKeyring {
>     keyId;
|     client;
|     grantTokens; //= compliance/framework/aws-kms/aws-kms-mrk-aware-symmetric-keyring.txt#2.6
```

Node version 14.18

Using:  @aws-crypto/client-browser: ^3.1.0

tsconfig.json relevant info:
```
"target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
"jsx": "react-jsx"
```

**Comment by texastony** [comment]
@leopinzon ,

I cannot recreate this error with just the information you have provided us.
Can you share with us a minimum example JS package that produces this error?

Have you looked at our [example-browser](https://github.com/aws/aws-encryption-sdk-javascript/tree/master/modules/example-browser) module?

Share with us an example package, and we will do our best to resolve this.

**Comment by texastony** [comment]
@leopinzon I am closing this ticket due to in-activity.

If you can share with us an example of the issue, we would be happy to investigate more.

If you want to do that in a private forum, you would need to contact us via AWS Support.

If you have other questions, feel free to open a new issue with us.
