### ISSUE TITLE
@aws-crypto/kms-keyring-node dependency issue

### ISSUE THREAD

**Issue by d3mi3n** [aws/aws-encryption-sdk-javascript#922]
### Problem:

`@aws-crypto/kms-keyring-node` imports `@aws-crypto/material-management` in [this file](https://github.com/aws/aws-encryption-sdk-javascript/blob/master/modules/kms-keyring-node/src/kms_mrk_strict_multi_keyring_node.ts#L9), but `@aws-crypto/material-management` is not listed as a dependency

### Solution:

Add `@aws-crypto/material-management` as a dependency of `@aws-crypto/kms-keyring-node` or (if possible) use `@aws-crypto/material-management-node` which is a dependency already.

**Comment by ajewellamz** [comment]
https://github.com/aws/aws-encryption-sdk-javascript/pull/1018

**Comment by trevorpoppen** [comment]
Hello, I'm seeing this dependency issue rear it's head again in `"@aws-crypto/client-node": "^3.2.0"` ;

Import throwing the error is  `import { NodeAlgorithmSuite } from '@aws-crypto/material-management';` from `@aws-crypto/kms-keyring-node`;

I'm using PlugnPlay in Yarn 3.3.0 and typescript 4.9.3

**Comment by josecorella** [comment]
Hello @d3mi3n,

Major Version 4.0.0 of the AWS ESDK for JS has been released. This major version should address the problems you outline on this issue. Please let us know if you have any questions.

AWS Crypto Tools
