### ISSUE TITLE
RawRsaKeyringNode doesn't support Der format.

### ISSUE THREAD

**Issue by JefStat** [aws/aws-encryption-sdk-javascript#975]
### Problem:

Working with another customer who encrypts the some json fields with a data key generated from KMS and includes the data key in the json object as a base64 encoded string. After decrypting the data key with the KMS decrypt operation I cannot use the key in the RawRsaKeyringNode as it's now a buffer with a der format key.

### Solution:

Add a static method to convert a der format datakey to a pem string for the RawRsaKeyringNode constructor.

**Comment by JefStat** [comment]
This is a simplified example which fails 


```typescript
test('Github RawRSA keyring', async () => {
    // share constants between sender and receiver
    const KeyId = myCmk_keyId;
    const context = { ab: 'aba' };
    const anObject = {
      a: 'a',
      g: [1, 2, 3],
      EncryptedPrivateKey: ''
    };
    const kmsConfig = { region: 'us-east-1' };
    const client = new KMS(kmsConfig);

    // Sender creates data key encrypts a few fields and sends to receiver with encrypted private key
    const generateDataKey = { KeyId, KeyPairSpec: 'RSA_4096', EncryptionContext: context};
    const dataKeyRes = await client.generateDataKeyPair(generateDataKey).promise();

    const prefix = '-----BEGIN PRIVATE KEY-----\n';
    const postfix = '\n-----END PRIVATE KEY-----\n';
    const pemText = prefix +  dataKeyRes.PrivateKeyPlaintext?.toString('base64').match(/.{0,64}/g)?.join('\n') + postfix;
    const publicPemText = prefix +  dataKeyRes.PublicKey?.toString('base64').match(/.{0,64}/g)?.join('\n') + postfix;
    const krEncrypt = new RawRsaKeyringNode({
      keyName: 'k', keyNamespace: 'k', rsaKey: {
        privateKey: pemText, publicKey: publicPemText
      }
    });

    const encryptRes = await encrypt(krEncrypt, anObject.a);
    anObject.a = encryptRes.result.toString('base64');
    anObject.EncryptedPrivateKey = dataKeyRes.PrivateKeyCiphertextBlob?.toString('base64') || '';


    // Then on the recipient side
    const dataKeyDecrypt = await client.decrypt({CiphertextBlob: Buffer.from(anObject.EncryptedPrivateKey, 'base64'), KeyId, EncryptionContext: context}).promise();
    const dataKeyText = prefix + dataKeyDecrypt.Plaintext?.toString('base64').match(/.{0,64}/g)?.join('\n') + postfix;
    const keyring = new RawRsaKeyringNode({
      keyName: 'k', keyNamespace: 'k', rsaKey: {
        privateKey: dataKeyText
      }
    });
    const decryptRes = await decrypt(keyring, Buffer.from(anObject.a, 'base64'));
    expect(decryptRes.plaintext.toString('utf8')).toMatchInlineSnapshot();
  });```

```

Error: Failed to read asymmetric key

    at node:internal/crypto/cipher:79:12
    at RawRsaKeyringNode._wrapKey (/node_modules/@aws-crypto/raw-rsa-keyring-node/src/raw_rsa_keyring_node.ts:109:45)
    at RawRsaKeyringNode._onEncrypt (/node_modules/@aws-crypto/raw-keyring/src/raw_keyring_decorators.ts:38:17)
    at RawRsaKeyringNode.onEncrypt (/node_modules/@aws-crypto/material-management/src/keyring.ts:40:23)
    at NodeDefaultCryptographicMaterialsManager.getEncryptionMaterials (/node_modules/@aws-crypto/material-management-node/src/node_cryptographic_materials_manager.ts:73:22)
```

**Comment by texastony** [comment]
Howdy @JefStat,

While this a valid feature request,
I am afraid we are not interested in supporting the Der format.

The AWS Encryption SDK (ESDK) is implemented in several languages
(C, .NET, Java, JavaScript, Python).

As such, we are selective about the features the ESDK provides.
Supporting new features in a variety of
languages and execution environments is challenging.

While extending the RSA Keyring in Node to support Der is feasible,
we would rather focus our efforts on other features.

Customers who need to provide RSA keys, or any key material,
in a format not supported by the [ESDK Specification](https://github.com/awslabs/aws-encryption-sdk-specification/blob/master/framework/raw-rsa-keyring.md#rsa) will have
to apply a transform to their material such that the ESDK can accept it.

We are glad that you made this request, even if we cannot support it.

We will keep our ears open for other customer's requesting Der support.
If their is enough need,
we will consider adding Der support to our ESDK Specification.

Again, thank you for your time and interest.
If you have another feature request,
please feel free to open another issue here
or on the [ESDK Specification](https://github.com/awslabs/aws-encryption-sdk-specification).

Much Obliged,
AWS Crypto Tools
